# Generated by Django 5.0.6 on 2025-02-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_product_jewelryorder_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "รอดำเนินการ"),
                            ("in_progress", "กำลังดำเนินการ"),
                            ("completed", "สำเร็จ"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="jewelryorder",
            name="product",
        ),
    ]
