# Generated by Django 5.0.6 on 2025-03-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_chatmessage_taskstatus_remove_message_receiver_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jewelryorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "รอดำเนินการ"),
                    ("in_progress", "กำลังดำเนินการ"),
                    ("completed", "เสร็จสิ้น"),
                    ("shipped", "จัดส่งแล้ว"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jewelryorder",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="order_images/"),
        ),
        migrations.AlterField(
            model_name="jewelryorder",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
